version: "3.9"

services:
  #################################
  # Commerce Database
  #################################
  commerce-db:
    container_name: commerce-db
    build: ./backend/database-commerce
    ports:
      - "5433:5432"  # Host:Container
    volumes:
      - commerce_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: commerce_db
    networks:
      - internal_network

  #################################
  # Error Logging Database
  #################################
  error-db:
    container_name: error-db
    build: ./backend/database-error
    ports:
      - "5434:5432"  # Host:Container
    volumes:
      - error_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: error_db
    networks:
      - internal_network

  #################################
  # Redis Service
  #################################
  redis:
    image: redis:latest  # Pulls latest Redis image
    container_name: redis-cart
    ports:
      - "6379:6379"  # Redis default port
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - internal_network

  #################################
  # Cart Microservice
  #################################
  cart-service:
    container_name: cart-service
    build: ./backend/cart-service  
    ports:
      - "3007:3007"  
    depends_on:
      - redis  
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379 
    networks:
      - internal_network

  #################################
  # Login Microservice
  #################################
  login-service:
    container_name: login-service
    build: ./backend/login-service
    ports:
      - "3000:3000"  
    volumes:
      - ./Backend/login-service/firebase-service-account.json:/usr/src/app/firebase-service-account.json
    depends_on:
      - commerce-db
    environment:
      - NODE_ENV=production
      - DB_HOST=commerce-db  
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=commerce_db
    networks:
      - internal_network

  #################################
  # Order Microservice
  #################################
  order-service:
    container_name: order-service
    build: ./backend/order-service
    ports:
      - "5001:5001" 
    depends_on:
      - commerce-db
    networks:
      - internal_network

  #################################
  # Supplier Microservice
  #################################
  supplier-service:
    container_name: supplier-service
    build: ./backend/supplier-service
    ports:
      - "3008:3008"  
    depends_on:
      - commerce-db
    environment:
      - NODE_ENV=production
      - DB_HOST=commerce-db
      - commerce_db_port=5432
      - commerce_db_user=user
      - commerce_db_password=password
      - commerce_db_name=commerce_db
    networks:
      - internal_network
  #################################
  # Shop Microservice
  #################################
  shop-service:
    container_name: shop-service
    build: ./backend/shop-service
    ports:
      - "3006:3006"  
    depends_on:
      - commerce-db
    environment:
      - NODE_ENV=production
      - DB_HOST=commerce-db
      - commerce_db_port=5432
      - commerce_db_user=user
      - commerce_db_password=password
      - commerce_db_name=commerce_db
    networks:
      - internal_network

  #################################
  # Transaction Microservice
  #################################
  transaction-service:
    container_name: transaction-service
    build: ./backend/transaction-service
    ports:
      - "3009:3009"  
    depends_on:
      - commerce-db
    environment:
      - NODE_ENV=production
      - DB_HOST=commerce-db
      - commerce_db_port=5432
      - commerce_db_user=user
      - commerce_db_password=password
      - commerce_db_name=commerce_db
      - DATABASE_URL=postgresql://user:password@host.docker.internal:5433/commerce_db
    networks:
      - internal_network

  #################################
  # Cart Orchestrator 
  #################################
  cart-orchestrator:
    container_name: cart-orchestrator
    build: ./backend/cart-orchestrator  
    ports:
      - "4000:4000"  
    depends_on:
      - cart-service
    environment:
      - CART_SERVICE_URL=http://cart-service:3007  
    networks:
      - internal_network

volumes:
  commerce_pgdata:
    driver: local
  error_pgdata:
    driver: local
  redis-data:
    driver: local

networks:
  internal_network:
    driver: bridge
