# Use the official Node.js image from the Docker Hub
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json first to leverage Docker cache
COPY package*.json ./

# Install the dependencies specified in package.json
RUN npm install

# Copy the rest of the application files into the container
COPY . .

# Expose the port your app will run on
EXPOSE 3010

# Define the command to run your app
CMD ["node", "index.js"]
