# --- Stage 1: Build the application ---
    FROM eclipse-temurin:21-jdk AS build
    WORKDIR /app
    COPY . .
    RUN ./mvnw clean package -DskipTests
    
    # --- Stage 2: Run the application ---
    FROM eclipse-temurin:21-jdk
    WORKDIR /app
    COPY --from=build /app/target/PlaceAnOrderOrchestrator-0.0.1-SNAPSHOT.jar app.jar
    ENTRYPOINT ["java", "-jar", "app.jar"]
    